fix: update key from symbol to contactId about balance of token
onflow/FRW-iOS pull request #557
Opened 2024-11-21 17:21 UTC by zhouxl

(1) Beta and Beta.classic token displayed correctly in flow and evm network 
 (2) These two tokens send and move succeed between flow and evm accoount
 [ticket](https://github.com/Outblock/FRW-iOS/issues/550)

2024-11-21 23:06 UTC, jeden requested changes, later dismissed
A small request to remove code duplication, otherwise it looks qualitatively good

2024-11-21 23:06 UTC, jeden commented on FRW/Modules/Staking/Model/StakingInfo.swift
These 3 computed properties have two lines (almost) identical, so I would refactor this code to have one private property to calculate the rate:

```
private var coinRate: Double? { 
    let token = WalletManager.shared.flowToken
    return CoinRateCache.cache.getSummary(by: token?.contractId ?? "") ?? 0
}
```

and the implementation of the three properties is:

```
var tokenStakedASUSD: Double {
    return tokensStaked * self.coinRate
}

var dayRewardsASUSD: Double {
    return dayRewards * self.coinRate
}

var monthRewardsASUSD: Double {
    return monthRewards * self.coinRate
}
```

2024-11-21 23:41 UTC, lmcmz approved these changes

2024-11-22 10:34 UTC, zhouxl commented on FRW/Modules/Staking/Model/StakingInfo.swift
done

2024-11-22 11:04 UTC, lmcmz approved these changes

2024-11-22 11:12 UTC, merged