feat: update localizable
onflow/FRW-iOS pull request #649
Opened 2024-12-10 07:45 UTC by zhouxl

## Related Issue

#546 #545 #552 #554 #570 #544 #540 

## Summary of Changes

## Need Regression Testing

- [ ] Yes
- [ ] No

## Risk Assessment

- [ ] Low
- [ ] Medium
- [ ] High

## Additional Notes

## Screenshots (if applicable)

2024-12-10 07:47 UTC, lmcmz approved these changes

2024-12-10 21:18 UTC, jeden requested changes
I can't find the changes related to #540. Are these already implemented, just missing the language translations?

2024-12-10 21:18 UTC, jeden commented on FRW/Resource/en.lproj/Localizable.strings
At line 485 this doesn't seem to have been updated (ticket #544):

```
"no_account_found_msg" = "No results. Please check your input and try again.";
```

2024-12-19 09:37 UTC, zhouxl commented on FRW/Resource/en.lproj/Localizable.strings
fixed

2024-12-19 09:39 UTC, zhouxl commented
> I can't find the changes related to #540. Are these already implemented, just missing the language translations?

yes, Let me go to crowdin and check it out.

2024-12-19 19:51 UTC, hellolighten-team approved these changes

2024-12-19 19:53 UTC, jeden approved these changes

2024-12-20 05:16 UTC, merged